title: WaiKit Xiu's Homepage
page-top-title: WaiKit Xiu
top-section-bg-text: Artificial Intelligence
home-subtitle: WaiKit Xiu&ensp;|&ensp;修玮杰
copyright-text: '&copy; Sen Li 2023-2025. All Rights Reserved.'